### ISSUE TITLE
Missing a "edit on github button"

### ISSUE THREAD

**Issue by mscherer** [radanalyticsio/radanalyticsio.github.io#1]
I think "edit on github" would make clear to people that they can edit the site on github

**Comment by elmiko** [comment]
that's a nice idea, i thought about putting something on the community page about "contribute to this site". were you thinking like a ribbon graphic across the corner or something?

**Comment by mscherer** [comment]
Usually, what we have is something in the footer, along the privacy policy, and copyright stuff, who are also missing :)

**Comment by elmiko** [comment]
ah, ok. thanks for the suggestion, i'll look at some of other pages and look at creating a footer for this site too.

**Comment by elmiko** [comment]
added the "edit me on github" link in the top part of the navbar
