### ISSUE TITLE
add a valid certificate (via Let's Encrypt or similar) for radanalytics.io

### ISSUE THREAD

**Issue by willb** [radanalyticsio/radanalyticsio.github.io#11]
We want people to be able to use HTTPS!

(thanks to @portante for reminding me to file this)

**Comment by elmiko** [comment]
sounds good, i'm wondering if we should escalate up from let's encrypt and get a stronger cert?

**Comment by elmiko** [comment]
this has been addressed by moving the site to netlify and adding a letsencrypt cert through their infra. this pr completes the updates to the site #75
