### ISSUE TITLE
Spark Summit EU 2017 presentations on community page

### ISSUE THREAD

**Issue by mattf** [radanalyticsio/radanalyticsio.github.io#132]
@willb @elmiko @erikerlandson

**Comment by erikerlandson** [comment]
I've been waiting for them to drop the deck link (they seem to be linking the video before the decks this time around)

**Comment by willb** [comment]
I actually already did this [on a branch](https://github.com/radanalyticsio/radanalyticsio.github.io/tree/sseu2017).  I don't care about deck links because slideshare is so hostile.

**Comment by erikerlandson** [comment]
Possibly a slide design blunder - but I care a little about the deck because my last slide was full of links that I encouraged people to follow via the pdf.  However, I can very easily update the doc whenever they drop the decks

**Comment by willb** [comment]
@erikerlandson good point.  (We could add clickable links to the abstract, too.)
