### ISSUE TITLE
The suffix 'Pi' is missed in the class name (public class SparkContextProvider) in the test example

### ISSUE THREAD

**Issue by olegvn88** [radanalyticsio/radanalyticsio.github.io#147]
The suffix 'Pi' is missed in the class name (public class SparkContextProvider) and also this suffix is missed in created instances of this class in the test example here https://radanalytics.io/assets/my-first-radanalytics-app/sparkpi-java-spring.html

**Comment by elmiko** [comment]
thanks @olegvn88! patch is up now #149
