### ISSUE TITLE
Docker run fails when running the rad analytics site on Mac. 

### ISSUE THREAD

**Issue by sophwats** [radanalyticsio/radanalyticsio.github.io#171]
The following commands work as expected: 

`chmod -R go+rX .`
`docker build -t radanalytics.io .`

However, the docker run command gives an error: 
`docker run --rm -it -p 4000:4000 radanalytics.io` 

```
$ docker run --rm -it -p 4000:4000 radanalytics.io
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
Configuration file: /srv/site/_config.yml
            Source: /srv/site
       Destination: /srv/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.5.1 | Error:  Permission denied @ rb_sysopen - /srv/site/_site/community.html
```

**Comment by sophwats** [comment]
Deleting line 12 of the docker file, which previously held: 
`USER: 1001` 
causes the build error to disappear.

**Comment by elmiko** [comment]
we might just need to change the permissions on `/srv` to be owned by `1001:1001`
