### ISSUE TITLE
"Lightning talk" broken link (jiminy project tutorial)

### ISSUE THREAD

**Issue by ruivieira** [radanalyticsio/radanalyticsio.github.io#174]
The [Lightning talk](https://radanalytics.io/assets/project-jiminy/lightning) link on the [jiminy project tutorial](https://radanalytics.io/applications/project-jiminy) is broken.

**Comment by elmiko** [comment]
good spot @ruivieira!

i think we should make a deck for this, maybe we can talk about it on friday?

**Comment by ruivieira** [comment]
Of course! Sorry I've just spotted this on the live version.

**Comment by elmiko** [comment]
link has been removed for now while the deck is worked on
