### ISSUE TITLE
Change link on SparkPi page

### ISSUE THREAD

**Issue by rebeccaSimmonds19** [radanalyticsio/radanalyticsio.github.io#185]
[https://radanalytics.io/assets/my-first-radanalytics-app/sparkpi-java-spring.html](url)

![screen shot 2018-04-10 at 14 58 52](https://user-images.githubusercontent.com/22922596/38628321-fe7cfdde-3da8-11e8-9c12-ddfd28230f83.png)

The instructions link in this screen shot should take the user back to the first app page however it gives a 404. This needs changed as the link changed when the my first app was moved.

**Comment by elmiko** [comment]
thanks @rebeccaSimmonds19
