### ISSUE TITLE
get up and running with oshinko

### ISSUE THREAD

**Issue by mattf** [radanalyticsio/radanalyticsio.github.io#2]
there needs to be a getting started guide for oshinko.

it should provide a common basis for the tutorial applications to extend.

both the podded (walk-up) and extension (console native) deployments should be covered.

it should start from oc cluster up, but include a pointer to the openshift installation documents for anyone who wants to do more than an all-in-one deployment.

all the necessary s2i templates should be included.

**Comment by mattf** [comment]
cc @tmckayus @mpbarrett

**Comment by elmiko** [comment]
i was thinking about this last night, i'm wondering should we create a new top-level document titled something like "Getting Started", or should we just add a section to the tutorials pages about it?

**Comment by mattf** [comment]
top level, something similar to the old "download" tab (a visual, steps to get started, steps to verify things are working)

**Comment by elmiko** [comment]
ack

**Comment by elmiko** [comment]
closing this as it was covered by #12 and #14 , we still need something about the console extension but i think that is a moving target and we should open another issue.
