### ISSUE TITLE
Kubeflow example for Openshift

### ISSUE THREAD

**Issue by jarcher** [radanalyticsio/radanalyticsio.github.io#262]
Hope this is the correct place to open this ticket - has anyone created a template/script/doc on deploying Kubeflow or even better Kubeflow/Sheldon on OCP/minishift?

**Comment by elmiko** [comment]
We don't have an example or script for this on the site yet, but I know there have been some demonstrations in the wild. maybe @mattf has some pointers.

**Comment by willb** [comment]
@jarcher for the most part you can follow the upstream instructions -- there are some caveats, linked in [the troubleshooting docs](https://github.com/kubeflow/website/blob/master/content/docs/guides/troubleshooting.md#openshift)

**Comment by jarcher** [comment]
thanks will give it a shot..
