### ISSUE TITLE
Slides for "Apache Spark for Library Developers" talk no longer viewable

### ISSUE THREAD

**Issue by sophwats** [radanalyticsio/radanalyticsio.github.io#285]
Following the link on the Community page for "slides" under both part 1 and part 2 of the Apache Spark for Library Developers talk leads to a "suspended" slideshare account.  

https://www.slideshare.net/databricks/apache-spark-for-library-developers-with-erik-erlandson-and-william-benton
@willb

**Comment by elmiko** [comment]
confirmed, thanks @sophwats !

**Comment by elmiko** [comment]
@willb @erikerlandson is there a new location for the slides?

**Comment by elmiko** [comment]
thanks @willb
