### ISSUE TITLE
add more customization to the tutorial application menu

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/radanalyticsio.github.io#6]
as it stands now, the application tutorial menu (`_includes/menu_tutorial_application.html`) will create a tab link in the nav bar for a lightning talk slide deck link. if no deck exists then this link will be dead air. the template should be expanded, or new templates created, that will allow a developer to customize which links will appear in that menu.

this could either take the form of having multiple `menu_tutorial_application_*.html` files or possibly using front matter variables to control what appears.

**Comment by willb** [comment]
IMHO a frontmatter variable is the right way to go!

**Comment by elmiko** [comment]
that's kinda how i was leaning, thinking something along the lines of:

```
---
....
menu_items: lightning, someotherthing, someotherotherthing
---
```
