### ISSUE TITLE
STI->S2I?

### ISSUE THREAD

**Issue by pdmack** [radanalyticsio/radanalyticsio.github.io#64]
https://github.com/radanalyticsio/radanalyticsio.github.io/blob/master/resources.yaml#L185

**Comment by elmiko** [comment]
imo, we should probably just say "source-to-image", thoughts?

**Comment by elmiko** [comment]
oh, i see though, it's out of phase with the other description. hmm...

https://github.com/radanalyticsio/radanalyticsio.github.io/blob/master/resources.yaml#L30
