### ISSUE TITLE
add community collateral

### ISSUE THREAD

**Issue by mattf** [radanalyticsio/radanalyticsio.github.io#9]
we should have a section on the site that collects slides and recordings of community events

**Comment by elmiko** [comment]
+1, Will and i had been talking about this as well

**Comment by elmiko** [comment]
closing this, a presentations section has been added to the community page in this commit https://github.com/radanalyticsio/radanalyticsio.github.io/commit/e81f3f7c81eae46f37ff186edfc6c8ea29259b71
